version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout
      - run:
          name: Change dir
          command: cd .circleci
      - run:
          name: Run tests
          command: ./run_tests.sh
