version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    working_directory: ~/project/.circleci/

    steps:
      - checkout
      - run:
          name: Greeting
          command: ls
